name: php CD
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout

      - name: docker gub login
        uses: docker/login-action@v2
        with:
          username: 'dockerusername'
          password: 'dockerpassword'

      - name: docker build
        run: docker build -t mityuris/devops-marine .

      - name: docker push
        run: docker push mytyuris/devops-marine