name: php CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: php setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: composer setup
        uses: php-actions/composer@v6
      - name: phpunit setup
        uses: php-actions/phpunit@v3
      - name: dependencies
        uses: composer install
